REVOKE ALL ON ALL FUNCTIONS IN SCHEMA api FROM PUBLIC;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA api TO course_owner;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA api TO course_runtime;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA api TO course_migration;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA api TO course_publication;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA api TO course_target;

GRANT EXECUTE ON FUNCTION api.invoke(text,text,integer,jsonb,jsonb) TO workflow_worker;