<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql" Version="9.0.3"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.0"/>
        <PackageReference Include="JsonSchema.Net" Version="7.0.2"/>
    </ItemGroup>

</Project>
